### PR TITLE
Update packages section

### PR DESCRIPTION
**Pull request by dcrtantuco**
Awesome work!

This PR aims to update packages section
Added ruby and elixir ports

### CODE REVIEW

**Comment by marteinn** [comment]
Awesome, I love elixir :) One thing, could you base your PR from the develop-branch? (This project follows gitflow). Thanks!

**Comment by dcrtantuco** [comment]
@marteinn done! thanks :)

**Comment by darwintantuco** [comment]
I just notice current develop is not yet merged to master.

**Comment by marteinn** [comment]
@darwintantuco Thanks for the reminder, I just pushed out https://github.com/marteinn/The-Big-Username-Blacklist/releases/tag/v1.6.0 with the latest changes

**Comment by darwintantuco** [comment]
thanks! @marteinn

**Pull request merged**
